# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AudiobookshelfCli < Formula
  desc "Command-line interface for Audiobookshelf servers"
  homepage "https://github.com/LeeroyDing/audiobookshelf-cli"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.1/audiobookshelf-cli_Darwin_x86_64.tar.gz"
      sha256 "a2af7e547a40baa83ff2be6444e6e8e43a23267adefd7a9b9b25cd308832adac"

      define_method(:install) do
        bin.install "abs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.1/audiobookshelf-cli_Darwin_arm64.tar.gz"
      sha256 "e0ab146e2572cba9132ec3c7be388947179d4dd37e0d905a968fe72adef6199f"

      define_method(:install) do
        bin.install "abs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.1/audiobookshelf-cli_Linux_x86_64.tar.gz"
      sha256 "5ac6b138868295a59891077e39b21f7ef052cffce3e1c5cbe68027d1bc10965c"
      define_method(:install) do
        bin.install "abs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.1/audiobookshelf-cli_Linux_arm64.tar.gz"
      sha256 "a40a9c5e7b210217b470402ca79ae592b9a5d07cc8fe783115f24b8a073b1e03"
      define_method(:install) do
        bin.install "abs"
      end
    end
  end
end
