# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AudiobookshelfCli < Formula
  desc "Command-line interface for Audiobookshelf servers"
  homepage "https://github.com/LeeroyDing/audiobookshelf-cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.0/audiobookshelf-cli_Darwin_x86_64.tar.gz"
      sha256 "17cb0f44a0c26cba32724c4529d02a2cbc24c05279f73741098e1aa50da664fd"

      define_method(:install) do
        bin.install "abs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.0/audiobookshelf-cli_Darwin_arm64.tar.gz"
      sha256 "803eac90ade6105cbcbf7129867690dabce47e40d6dfeeb786e58f7159e85076"

      define_method(:install) do
        bin.install "abs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.0/audiobookshelf-cli_Linux_x86_64.tar.gz"
      sha256 "26e412c3718c77ee5e412ce16ba45055024ef34c222412f90fc78004f0952b1a"
      define_method(:install) do
        bin.install "abs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeeroyDing/audiobookshelf-cli/releases/download/v1.3.0/audiobookshelf-cli_Linux_arm64.tar.gz"
      sha256 "eef6761940de019e8726c4ae48140ac3494663b0d40f8ba2870e1cb267be9c92"
      define_method(:install) do
        bin.install "abs"
      end
    end
  end
end
