# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SeerrCli < Formula
  desc "Command-line interface for Seerr and Overseerr media managers"
  homepage "https://github.com/LeeroyDing/seerr-cli"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LeeroyDing/seerr-cli/releases/download/v0.11.1/seerr-cli_Darwin_x86_64.tar.gz"
      sha256 "e79dfcc96162ce60c44a46f9018c87b3dd3733afb46e40fdec26640d1195796a"

      define_method(:install) do
        bin.install "seerr-cli" => "seerr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LeeroyDing/seerr-cli/releases/download/v0.11.1/seerr-cli_Darwin_arm64.tar.gz"
      sha256 "737be14fb070dd4f1f41167e66baecd6bd0d2e0f4fa36b0232bb153aaf76a674"

      define_method(:install) do
        bin.install "seerr-cli" => "seerr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeeroyDing/seerr-cli/releases/download/v0.11.1/seerr-cli_Linux_x86_64.tar.gz"
      sha256 "72e7a9a7a522758a91bcc510624a980613c151b10939de4fc4696a850d698c29"
      define_method(:install) do
        bin.install "seerr-cli" => "seerr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeeroyDing/seerr-cli/releases/download/v0.11.1/seerr-cli_Linux_arm64.tar.gz"
      sha256 "8db81293f87792a83df74a5e02922230f9e9b9318ccdfef04ff3dd31cb656c83"
      define_method(:install) do
        bin.install "seerr-cli" => "seerr"
      end
    end
  end
end
